# Generated by Django 3.2.13 on 2022-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrollmentscheduleevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
