[tool.pytest.ini_options]
addopts = "-v"
testpaths = "slu/"
python_files = "tests.py test_*.py"
norecursedirs = ".git __pycache__"
filterwarnings = [
    "ignore::DeprecationWarning:kombu.*",
    "ignore::DeprecationWarning:django_js_reverse.*",
]

[tool.coverage.run]
include = [
    "slu/*"
]
omit = [
    "*migrations*",
    "*tests*",
]

[tool.isort]
profile = "black"
