# Generated by Django 3.2.13 on 2022-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragonpayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('description', models.TextField()),
                ('channel_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('f', 'Failed'), ('s', 'Success')], default='p', max_length=2)),
                ('settlement_date', models.DateTimeField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
