# Generated by Django 3.2.13 on 2022-05-31 10:16

from django.db import migrations, models
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukasTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('reference_code', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('transaction', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
