# Generated by Django 3.2.13 on 2022-06-08 03:09

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20220607_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragonpayChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('proc_id', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='dragonpaytransaction',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='dragonpaytransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='bukastransaction',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('F', 'Failed'), ('D', 'Disbursed')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "F": "Failed",\n    "D": "Disbursed"\n}\n```', max_length=2),
        ),
        migrations.AlterField(
            model_name='bukastransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bukastransaction',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bukastransaction',
            name='transaction',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bukastransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dragonpaytransaction',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Success')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "F": "Failed",\n    "S": "Success"\n}\n```', max_length=2),
        ),
        migrations.AddField(
            model_name='dragonpaytransaction',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.dragonpaychannel'),
            preserve_default=False,
        ),
    ]
