# Generated by Django 3.2.13 on 2022-06-12 17:41

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20220610_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='payment.statementofaccount')),
            ],
            options={
                'verbose_name_plural': 'Statement Line Categories',
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='statementline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='payment.statementlinecategory'),
        ),
    ]
