# Generated by Django 3.2.13 on 2022-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20220612_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragonpaychannel',
            name='addon_fixed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='dragonpaychannel',
            name='addon_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dragonpaytransaction',
            name='addon_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
