# Generated by Django 3.2.13 on 2022-06-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20220621_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementofaccount',
            old_name='min_amount_due',
            new_name='min_amount',
        ),
    ]
