# Generated by Django 3.2.13 on 2022-06-22 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_min_amount_due_statementofaccount_min_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bukastransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dragonpaytransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='overthecountertransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={},
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
