# Generated by Django 3.2.13 on 2022-06-29 09:33

from django.db import migrations
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20220624_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukastransaction',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('F', 'Failed'), ('FF', 'For Funding'), ('D', 'Disbursed')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "F": "Failed",\n    "FF": "For Funding",\n    "D": "Disbursed"\n}\n```', max_length=2),
        ),
    ]
