# Generated by Django 3.2.14 on 2022-07-26 00:14

from django.db import migrations, models
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20220726_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='overthecountertransaction',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overthecountertransaction',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Success'), ('SS', 'Settled')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "F": "Failed",\n    "S": "Success",\n    "SS": "Settled"\n}\n```', max_length=2),
        ),
    ]
