# Generated by Django 3.2.14 on 2022-07-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0024_auto_20220726_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementline',
            name='ref_ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='statementline',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
