# Generated by Django 3.2.14 on 2022-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20220727_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiertransaction',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
