# Generated by Django 3.2.14 on 2022-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_dragonpaytransaction_channel_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='jv_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsettlement',
            name='jv_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='jv_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
