# Generated by Django 3.2.14 on 2022-07-30 11:38

from django.db import migrations
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_auto_20220730_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='overthecountertransaction',
            name='bank',
            field=slu.framework.models.TextChoiceField(choices=[('BDO', 'Banco de Oro'), ('PNB', 'Philippine National Bank'), ('MBTC', 'Metrobank'), ('LBP', 'Land Bank of the Philippines')], default='BDO', help_text='```json\n{\n    "BDO": "Banco de Oro",\n    "PNB": "Philippine National Bank",\n    "MBTC": "Metrobank",\n    "LBP": "Land Bank of the Philippines"\n}\n```', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsettlement',
            name='payment_method',
            field=slu.framework.models.TextChoiceField(choices=[('DP', 'Dragonpay'), ('B', 'Bukas'), ('OTC', 'Bank'), ('C', 'School Cashier')], help_text='```json\n{\n    "DP": "Dragonpay",\n    "B": "Bukas",\n    "OTC": "Bank",\n    "C": "School Cashier"\n}\n```', max_length=3),
        ),
    ]
