# Generated by Django 3.2.14 on 2022-07-31 00:32

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0014_academicyear_semester'),
        ('payment', '0032_journalvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragonpayKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('merchant_id', models.CharField(max_length=255)),
                ('merchant_password', models.CharField(max_length=255)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_accounts.school')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
