# Generated by Django 3.2.14 on 2022-09-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_dragonpaychannel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonpaychannel',
            name='addon_fixed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed SLU charge', max_digits=9),
        ),
        migrations.AlterField(
            model_name='dragonpaychannel',
            name='addon_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Merchant percentage charge', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='dragonpaychannel',
            name='description',
            field=models.TextField(help_text='Channel name'),
        ),
    ]
