# Generated by Django 3.2.14 on 2022-10-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_auto_20220912_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementofaccount',
            name='has_remaining_balance',
            field=models.BooleanField(default=True),
        ),
    ]
