# Generated by Django 3.2.14 on 2022-11-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_statementofaccount_has_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
