# Generated by Django 3.2.13 on 2022-06-05 20:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0008_auto_20220605_2059'),
        ('core_students', '0003_auto_20220604_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', slu.framework.models.TextChoiceField(choices=[('PE', 'Pre-Enrollment'), ('PED', 'Pre-Enrolled'), ('E', 'Enrollment'), ('ED', 'Enrolled'), ('I', 'Invalid')], default='PE', help_text='```json\n{\n    "PE": "Pre-Enrollment",\n    "PED": "Pre-Enrolled",\n    "E": "Enrollment",\n    "ED": "Enrolled",\n    "I": "Invalid"\n}\n```', max_length=3)),
                ('current_address', models.CharField(max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=255, null=True)),
                ('personal_email', models.EmailField(max_length=254, null=True)),
                ('slu_email', models.EmailField(max_length=254, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_living_with_parents', models.BooleanField(default=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_address', models.CharField(max_length=255)),
                ('emergency_contact_phone_no', models.CharField(max_length=255)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_employee_dependent', models.BooleanField(default=False)),
                ('dependent_employee_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dependent_relationship', slu.framework.models.TextChoiceField(blank=True, choices=[('F', 'Father'), ('M', 'Mother')], help_text='```json\n{\n    "F": "Father",\n    "M": "Mother"\n}\n```', max_length=2, null=True)),
                ('step', slu.framework.models.IntegerChoiceField(choices=[(0, 'Start'), (1, 'Information'), (2, 'Discounts'), (3, 'Subjects'), (4, 'Payment'), (5, 'Enrollment Status')], default=0, help_text='```json\n{\n    "0": "Start",\n    "1": "Information",\n    "2": "Discounts",\n    "3": "Subjects",\n    "4": "Payment",\n    "5": "Enrollment Status"\n}\n```', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('curriculum_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_cms.curriculumperiod')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='student',
            name='slu_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('F', 'Filipino')], help_text='```json\n{\n    "F": "Filipino"\n}\n```', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='civil_status',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed')], help_text='```json\n{\n    "S": "Single",\n    "M": "Married",\n    "W": "Widowed"\n}\n```', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='```json\n{\n    "M": "Male",\n    "F": "Female"\n}\n```', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('F', 'Filipino')], help_text='```json\n{\n    "F": "Filipino"\n}\n```', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=slu.framework.models.TextChoiceField(choices=[('S', 'Student'), ('FA', 'Freshmen Applicant')], default='S', help_text='```json\n{\n    "S": "Student",\n    "FA": "Freshmen Applicant"\n}\n```', max_length=2),
        ),
        migrations.CreateModel(
            name='SiblingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id_number', models.CharField(max_length=255)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_discounts', to='core_students.enrollment')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EnrollmentSubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', slu.framework.models.TextChoiceField(choices=[('FA', 'For Approval'), ('A', 'Approved'), ('R', 'Rejected')], default='FA', help_text='```json\n{\n    "FA": "For Approval",\n    "A": "Approved",\n    "R": "Rejected"\n}\n```', max_length=2)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_schedules', to='core_students.enrollment')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_cms.schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_students.student'),
        ),
    ]
