# Generated by Django 3.2.13 on 2022-06-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0004_auto_20220605_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentsubjectschedule',
            old_name='schedule',
            new_name='subject_class',
        ),
    ]
