# Generated by Django 3.2.13 on 2022-06-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0014_auto_20220612_0840'),
        ('core_students', '0005_rename_schedule_enrollmentsubjectschedule_subject_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsubjectschedule',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_cms.class'),
        ),
    ]
