# Generated by Django 3.2.13 on 2022-06-16 13:59

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0008_alter_enrollment_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='year_end',
            field=models.PositiveIntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='year_start',
            field=models.PositiveIntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('R', 'Regular'), ('S', 'Scholar'), ('I', 'International')], default='R', help_text='```json\n{\n    "R": "Regular",\n    "S": "Scholar",\n    "I": "International"\n}\n```', max_length=2),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='emergency_contact_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='emergency_contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='emergency_contact_phone_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EnrolledClassGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', slu.framework.models.TextChoiceField(choices=[('P', 'Passed'), ('Y', 'Yearly'), ('F', 'Failed'), ('INC', 'Incomplete'), ('W', 'Withdrawn'), ('UW', 'Unauthorized Withdrawal')], help_text='```json\n{\n    "P": "Passed",\n    "Y": "Yearly",\n    "F": "Failed",\n    "INC": "Incomplete",\n    "W": "Withdrawn",\n    "UW": "Unauthorized Withdrawal"\n}\n```', max_length=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('enrolled_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_students.enrollmentsubjectschedule')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
