# Generated by Django 3.2.13 on 2022-06-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0020_auto_20220617_0309'),
        ('core_students', '0009_auto_20220616_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledclassgrade',
            name='enrolled_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='core_students.enrollmentsubjectschedule'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core_students.student'),
        ),
        migrations.AlterField(
            model_name='enrollmentsubjectschedule',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='core_cms.class'),
        ),
    ]
