# Generated by Django 3.2.13 on 2022-06-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0024_alter_curriculumsubject_curriculum_period'),
        ('core_students', '0012_rename_enrollment_subject_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledclass',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to='core_students.enrollment'),
        ),
        migrations.AlterField(
            model_name='enrolledclass',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core_cms.class'),
        ),
    ]
