# Generated by Django 3.2.13 on 2022-06-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0013_auto_20220629_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledclassgrade',
            old_name='rate',
            new_name='grade',
        ),
    ]
