# Generated by Django 3.2.13 on 2022-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0014_rename_rate_enrolledclassgrade_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='slu_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
