# Generated by Django 3.2.13 on 2022-07-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0025_discount'),
        ('core_students', '0015_auto_20220701_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_enrollments', to='core_cms.discount'),
        ),
    ]
