# Generated by Django 3.2.13 on 2022-07-24 14:54

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0030_auto_20220724_2249'),
        ('core_students', '0017_auto_20220710_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='general_weighted_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grading_status',
            field=slu.framework.models.TextChoiceField(choices=[('PN', 'Pending'), ('P', 'Passed'), ('F', 'Failed')], default='PN', help_text='```json\n{\n    "PN": "Pending",\n    "P": "Passed",\n    "F": "Failed"\n}\n```', max_length=2),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='remark_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_enrollments', to='core_cms.remarkcode'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_enrollments', to='core_cms.discount'),
        ),
    ]
