# Generated by Django 3.2.13 on 2022-07-25 11:25

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0014_academicyear_semester'),
        ('core_cms', '0031_curriculumperiod_order'),
        ('core_students', '0018_auto_20220724_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('A', 'Allowed'), ('TA', 'Temporarily Allowed'), ('BWOB', 'Blocked with Outstanding Balance'), ('BWFS', 'Blocked with Failed Subject'), ('BWOBFG', 'Blocked with Outstanding Balance and Failed Grade')], help_text='```json\n{\n    "A": "Allowed",\n    "TA": "Temporarily Allowed",\n    "BWOB": "Blocked with Outstanding Balance",\n    "BWFS": "Blocked with Failed Subject",\n    "BWOBFG": "Blocked with Outstanding Balance and Failed Grade"\n}\n```', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_for_manual_tagging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core_accounts.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_students', to='core_cms.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_curriculum_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='core_cms.curriculumperiod'),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_students', to='core_cms.curriculum'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('A', 'Allowed'), ('TA', 'Temporarily Allowed'), ('BWOB', 'Blocked with Outstanding Balance'), ('BWFS', 'Blocked with Failed Subject'), ('BWOBFG', 'Blocked with Outstanding Balance and Failed Grade')], help_text='```json\n{\n    "A": "Allowed",\n    "TA": "Temporarily Allowed",\n    "BWOB": "Blocked with Outstanding Balance",\n    "BWFS": "Blocked with Failed Subject",\n    "BWOBFG": "Blocked with Outstanding Balance and Failed Grade"\n}\n```', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='next_curriculum_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_students', to='core_cms.curriculumperiod'),
        ),
        migrations.AlterField(
            model_name='enrolledclassgrade',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('PN', 'Pending'), ('P', 'Passed'), ('Y', 'Yearly'), ('F', 'Failed'), ('INC', 'Incomplete'), ('W', 'Withdrawn'), ('UW', 'Unauthorized Withdrawal')], help_text='```json\n{\n    "PN": "Pending",\n    "P": "Passed",\n    "Y": "Yearly",\n    "F": "Failed",\n    "INC": "Incomplete",\n    "W": "Withdrawn",\n    "UW": "Unauthorized Withdrawal"\n}\n```', max_length=5),
        ),
    ]
