# Generated by Django 3.2.13 on 2022-07-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0019_alter_enrolledclassgrade_status'),
        ('core_students', '0019_auto_20220725_1925'),
    ]

    operations = [
    ]
