# Generated by Django 3.2.13 on 2022-07-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0031_curriculumperiod_order'),
        ('core_students', '0022_auto_20220728_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='miscellaneous_fee_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misc_enrollments', to='core_cms.feespecification'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='other_fee_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_enrollments', to='core_cms.feespecification'),
        ),
    ]
