# Generated by Django 3.2.14 on 2022-07-31 00:54

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0023_auto_20220728_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', slu.framework.models.TextChoiceField(choices=[('ES', 'Enrollment Started'), ('EE', 'Enrollment Ended')], help_text='```json\n{\n    "ES": "Enrollment Started",\n    "EE": "Enrollment Ended"\n}\n```', max_length=12)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core_students.enrollment')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
