# Generated by Django 3.2.14 on 2022-08-03 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0014_academicyear_semester'),
        ('core_students', '0024_enrollmentevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='curriculum_period',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_curriculum_period',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_curriculum_period',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='year_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core_accounts.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
