# Generated by Django 3.2.14 on 2022-08-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0035_alter_curriculumsubject_curriculum'),
        ('core_students', '0025_auto_20220804_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledclass',
            name='curriculum_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_classes', to='core_cms.curriculumsubject'),
        ),
        migrations.AddField(
            model_name='enrolledclass',
            name='subject_equivalent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_classes', to='core_cms.subject'),
        ),
    ]
