# Generated by Django 3.2.14 on 2022-08-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0026_auto_20220804_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledclass',
            old_name='subject_equivalent',
            new_name='equivalent_subject',
        ),
    ]
