# Generated by Django 3.2.14 on 2022-09-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0027_rename_subject_equivalent_enrolledclass_equivalent_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledclass',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_classes', to='core_students.student'),
        ),
    ]
