# Generated by Django 3.2.14 on 2022-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0029_auto_20220906_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
