# Generated by Django 3.2.14 on 2022-10-06 23:42

from django.db import migrations, models
import django.db.models.deletion
import slu.core.students.models
import slu.framework.models
import slu.framework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0040_classgradestate'),
        ('core_students', '0031_auto_20220926_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralWeightedAverageSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file_id', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to=slu.core.students.models.gwa_sheet_file_path, validators=[slu.framework.validators.csv_file_validator])),
                ('status', slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('O', 'Processing'), ('F', 'Failed'), ('C', 'Completed')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "O": "Processing",\n    "F": "Failed",\n    "C": "Completed"\n}\n```', max_length=2)),
                ('error_message', models.TextField(blank=True)),
                ('success', models.IntegerField(default=0, help_text='Successful entries')),
                ('invalid', models.IntegerField(default=0, help_text='Entries with student IDs not found')),
                ('total', models.IntegerField(default=0, help_text='Total processed data')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='general_weighted_average',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='grading_status',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='remark_code',
        ),
        migrations.CreateModel(
            name='EnrollmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('general_weighted_average', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pass_percentage', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('grading_status', slu.framework.models.TextChoiceField(choices=[('PN', 'Pending'), ('P', 'Passed'), ('F', 'Failed')], default='PN', help_text='```json\n{\n    "PN": "Pending",\n    "P": "Passed",\n    "F": "Failed"\n}\n```', max_length=2)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='core_students.enrollment')),
                ('remark_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core_cms.remarkcode')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
