# Generated by Django 3.2.14 on 2022-10-25 11:44

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0032_auto_20221007_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', slu.framework.models.TextChoiceField(choices=[('CS', 'Change Schedule'), ('OP', 'Open a Class'), ('AS', 'Add Subject'), ('PW', 'Partial Withdraw'), ('FW', 'Full Withdraw')], default='CS', help_text='```json\n{\n    "CS": "Change Schedule",\n    "OP": "Open a Class",\n    "AS": "Add Subject",\n    "PW": "Partial Withdraw",\n    "FW": "Full Withdraw"\n}\n```', max_length=2)),
                ('status', slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('IR', 'In Review'), ('A', 'Approved'), ('R', 'Rejected')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "IR": "In Review",\n    "A": "Approved",\n    "R": "Rejected"\n}\n```', max_length=2)),
                ('request_no', models.CharField(max_length=255, null=True)),
                ('detail', models.TextField()),
                ('reason', models.TextField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core_students.student')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
