# Generated by Django 3.2.14 on 2022-10-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_students', '0034_auto_20221026_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core_students.studentrequest_set+', to='contenttypes.contenttype'),
        ),
    ]
