# Generated by Django 3.2.14 on 2022-10-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0035_studentrequest_polymorphic_ctype'),
        ('core_students', '0035_studentrequestreviewhistory'),
    ]

    operations = [
    ]
