# Generated by Django 3.2.14 on 2022-10-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0036_merge_20221026_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeschedulerequest',
            name='studentrequest_ptr',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentrequestreviewhistory',
            name='request',
        ),
        migrations.RemoveField(
            model_name='studentrequestreviewhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddSubjectRequest',
        ),
        migrations.DeleteModel(
            name='ChangeScheduleRequest',
        ),
        migrations.DeleteModel(
            name='StudentRequest',
        ),
        migrations.DeleteModel(
            name='StudentRequestReviewHistory',
        ),
    ]
