# Generated by Django 3.2.14 on 2022-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0038_addsubjectrequest_changeschedulerequest_studentrequest_studentrequestreviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slu_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
