# Generated by Django 3.2.14 on 2022-11-01 10:42

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0040_auto_20221101_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenClassRequest',
            fields=[
                ('studentrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_students.studentrequest')),
                ('status', slu.framework.models.TextChoiceField(choices=[('P', 'Pending'), ('FA', 'For Approval'), ('FE', 'For Encoding'), ('E', 'Encoded'), ('R', 'Rejected')], default='P', help_text='```json\n{\n    "P": "Pending",\n    "FA": "For Approval",\n    "FE": "For Encoding",\n    "E": "Encoded",\n    "R": "Rejected"\n}\n```', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('core_students.studentrequest',),
        ),
    ]
