# Generated by Django 3.2.14 on 2022-11-01 11:41

from django.db import migrations
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0041_openclassrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledclass',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('R', 'Reserved'), ('E', 'Enrolled'), ('V', 'Void')], default='R', help_text='```json\n{\n    "R": "Reserved",\n    "E": "Enrolled",\n    "V": "Void"\n}\n```', max_length=2),
        ),
    ]
