# Generated by Django 3.2.14 on 2022-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0042_alter_enrolledclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
