# Generated by Django 3.2.13 on 2022-07-13 09:41

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit_trail', '0002_traillog_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traillog',
            old_name='user',
            new_name='actor_name',
        ),
        migrations.AddField(
            model_name='traillog',
            name='actor_ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_logs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='traillog',
            name='actor_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traillog',
            name='actor_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traillog',
            name='log_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traillog',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='traillog',
            name='target_ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_logs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='traillog',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traillog',
            name='action',
            field=slu.framework.models.TextChoiceField(choices=[('G', 'Generic'), ('C', 'Created'), ('U', 'Updated'), ('D', 'Deleted')], help_text='```json\n{\n    "G": "Generic",\n    "C": "Created",\n    "U": "Updated",\n    "D": "Deleted"\n}\n```', max_length=2),
        ),
        migrations.AlterField(
            model_name='traillog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
