# Generated by Django 3.2.13 on 2022-05-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0002_school_ref_id'),
        ('core_cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.AddField(
            model_name='course',
            name='degree_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='core_accounts.School'),
        ),
        migrations.AlterField(
            model_name='course',
            name='accredited_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Associate/Certofocate'), ('B', 'Bachelor Degree'), ('M', 'Masteral'), ('D', 'Doctoral'), ('P', 'Post Graduate'), ('1', 'Special Program')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('Y', 'Year'), ('M', 'Month')], default='Y', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
