# Generated by Django 3.2.13 on 2022-05-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0003_auto_20220530_0357'),
        ('core_cms', '0002_auto_20220530_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core_accounts.School'),
        ),
    ]
