# Generated by Django 3.2.13 on 2022-05-31 04:40

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0003_auto_20220530_0357'),
        ('core_cms', '0003_alter_course_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ref_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('prebaccm', models.CharField(max_length=100)),
                ('prebaccf', models.CharField(max_length=100)),
                ('baccm', models.CharField(max_length=100)),
                ('baccf', models.CharField(max_length=100)),
                ('postbaccm', models.CharField(max_length=100)),
                ('postbaccf', models.CharField(max_length=100)),
                ('msm', models.CharField(max_length=100)),
                ('msf', models.CharField(max_length=100)),
                ('docm', models.CharField(max_length=100)),
                ('docf', models.CharField(max_length=100)),
                ('gprebaccm', models.CharField(max_length=100)),
                ('gprebaccf', models.CharField(max_length=100)),
                ('gbaccm', models.CharField(max_length=100)),
                ('gbaccf', models.CharField(max_length=100)),
                ('gpostbaccm', models.CharField(max_length=100)),
                ('gpostbaccf', models.CharField(max_length=100)),
                ('gmsm', models.CharField(max_length=100)),
                ('gmsf', models.CharField(max_length=100)),
                ('gdocm', models.CharField(max_length=100)),
                ('gdocf', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='course',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='no_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='ref_id',
            field=models.CharField(db_index=True, default='code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='school_buildings', to='core_accounts.School'),
        ),
        migrations.AddField(
            model_name='building',
            name='sub_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='ref_id',
            field=models.CharField(default='code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core_accounts.school'),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Associate/Certificate'), ('B', 'Bachelor Degree'), ('M', 'Masteral'), ('D', 'Doctoral'), ('P', 'Post Graduate'), ('1', 'Special Program')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core_cms.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core_cms.classification'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='furniture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core_accounts.school'),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='wing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core_cms.discipline'),
        ),
    ]
