# Generated by Django 3.2.13 on 2022-06-01 01:52

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0006_auto_20220601_0152'),
        ('core_cms', '0004_auto_20220531_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ref_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('group_course', models.TextField(blank=True, null=True)),
                ('is_gen_ed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_groupings', to='core_accounts.department')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
