# Generated by Django 3.2.13 on 2022-06-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0006_auto_20220601_0152'),
        ('core_cms', '0005_subjectgrouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_no',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_no_course_number',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type_subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='classification',
            field=models.CharField(blank=True, choices=[('F', 'BSIM/BLIS'), ('D', 'DAP'), ('G', 'Graduate'), ('L', 'LAW'), ('M', 'MEDICINE'), ('P', 'PE (Minor)'), ('R', 'RSTC'), ('N', 'NSTP'), ('NONE', 'Normal Subject')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='descriptive_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='descriptive_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.CharField(blank=True, choices=[('Y', 'Yearly'), ('S', 'Semestral'), ('M', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='grouping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouping_subjects', to='core_cms.subjectgrouping'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_lab_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_professional_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='lab_category',
            field=models.CharField(blank=True, choices=[('A', 'Accounting'), ('C', 'Computer'), ('G', 'Graduate Program'), ('L', 'Laboratory'), ('W', 'Law'), ('M', 'Medicine'), ('P', 'PE'), ('R', 'Religion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='no_of_hours',
            field=models.FloatField(blank=True, help_text='Only for Medicine Subjects', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='ref_id',
            field=models.CharField(default='code', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core_accounts.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('P', 'Pre-Requisite'), ('C', 'Co-Requisite')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='type_subjects',
            field=models.ManyToManyField(blank=True, to='core_cms.Subject'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_rooms', to='core_cms.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_rooms', to='core_cms.classification'),
        ),
        migrations.AlterField(
            model_name='room',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_rooms', to='core_accounts.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('P', 'Pre-Requisite'), ('C', 'Co-Requisite')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.FloatField(default=0, help_text='Only for Non-Medicine Subjects'),
        ),
    ]
