# Generated by Django 3.2.13 on 2022-06-04 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0006_auto_20220601_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('semester', models.CharField(blank=True, choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], max_length=50, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='year_level',
        ),
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='effective_end_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='effective_semester',
            field=models.CharField(choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], default='FS', max_length=50),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='effective_start_year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='ref_id',
            field=models.CharField(default='code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='category_rate',
            field=models.CharField(blank=True, choices=[('PE', 'Profession Education'), ('NP', 'Non-Professional'), ('ITR', 'IT Rate'), ('NR', 'Nurse Rate'), ('LR', 'LLB Rate'), ('G', 'Graduate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='subject_class',
            field=models.CharField(blank=True, choices=[('M', 'Major'), ('E', 'Elective'), ('S', 'Specialization')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='lab_wk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='lec_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='curriculumsubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_curriculum_periods', to='core_cms.subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CurriculumConfiguration',
        ),
        migrations.DeleteModel(
            name='YearLevel',
        ),
        migrations.AddField(
            model_name='curriculumperiod',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_periods', to='core_cms.curriculum'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='curriculum_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core_cms.curriculumperiod'),
            preserve_default=False,
        ),
    ]
