# Generated by Django 3.2.13 on 2022-06-05 20:59

from django.db import migrations
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0007_auto_20220604_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('A', 'Associate/Certificate'), ('B', 'Bachelor Degree'), ('M', 'Masteral'), ('D', 'Doctoral'), ('P', 'Post Graduate'), ('1', 'Special Program')], help_text='```json\n{\n    "A": "Associate/Certificate",\n    "B": "Bachelor Degree",\n    "M": "Masteral",\n    "D": "Doctoral",\n    "P": "Post Graduate",\n    "1": "Special Program"\n}\n```', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_unit',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('Y', 'Year'), ('M', 'Month')], default='Y', help_text='```json\n{\n    "Y": "Year",\n    "M": "Month"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='effective_semester',
            field=slu.framework.models.TextChoiceField(choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], default='FS', help_text='```json\n{\n    "FS": "First Semester",\n    "SS": "Second Semester",\n    "S": "Summer"\n}\n```', max_length=50),
        ),
        migrations.AlterField(
            model_name='curriculumperiod',
            name='semester',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], help_text='```json\n{\n    "FS": "First Semester",\n    "SS": "Second Semester",\n    "S": "Summer"\n}\n```', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='category_rate',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('PE', 'Profession Education'), ('NP', 'Non-Professional'), ('ITR', 'IT Rate'), ('NR', 'Nurse Rate'), ('LR', 'LLB Rate'), ('G', 'Graduate')], help_text='```json\n{\n    "PE": "Profession Education",\n    "NP": "Non-Professional",\n    "ITR": "IT Rate",\n    "NR": "Nurse Rate",\n    "LR": "LLB Rate",\n    "G": "Graduate"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='subject_class',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('M', 'Major'), ('E', 'Elective'), ('S', 'Specialization')], help_text='```json\n{\n    "M": "Major",\n    "E": "Elective",\n    "S": "Specialization"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=slu.framework.models.TextChoiceField(choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], default='FS', help_text='```json\n{\n    "FS": "First Semester",\n    "SS": "Second Semester",\n    "S": "Summer"\n}\n```', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=slu.framework.models.TextChoiceField(choices=[('S', 'Semester'), ('T', 'Trimester')], default='S', help_text='```json\n{\n    "S": "Semester",\n    "T": "Trimester"\n}\n```', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='day',
            field=slu.framework.models.TextChoiceField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], default='M', help_text='```json\n{\n    "M": "Monday",\n    "T": "Tuesday",\n    "W": "Wednesday",\n    "TH": "Thursday",\n    "F": "Friday",\n    "S": "Saturday"\n}\n```', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], help_text='```json\n{\n    "LEC": "Lecture",\n    "LAB": "Laboratory"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='classification',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('F', 'BSIM/BLIS'), ('D', 'DAP'), ('G', 'Graduate'), ('L', 'LAW'), ('M', 'MEDICINE'), ('P', 'PE (Minor)'), ('R', 'RSTC'), ('N', 'NSTP'), ('NONE', 'Normal Subject')], help_text='```json\n{\n    "F": "BSIM/BLIS",\n    "D": "DAP",\n    "G": "Graduate",\n    "L": "LAW",\n    "M": "MEDICINE",\n    "P": "PE (Minor)",\n    "R": "RSTC",\n    "N": "NSTP",\n    "NONE": "Normal Subject"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='duration',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('Y', 'Yearly'), ('S', 'Semestral'), ('M', 'Monthly')], help_text='```json\n{\n    "Y": "Yearly",\n    "S": "Semestral",\n    "M": "Monthly"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab_category',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('A', 'Accounting'), ('C', 'Computer'), ('G', 'Graduate Program'), ('L', 'Laboratory'), ('W', 'Law'), ('M', 'Medicine'), ('P', 'PE'), ('R', 'Religion')], help_text='```json\n{\n    "A": "Accounting",\n    "C": "Computer",\n    "G": "Graduate Program",\n    "L": "Laboratory",\n    "W": "Law",\n    "M": "Medicine",\n    "P": "PE",\n    "R": "Religion"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_type',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('N', 'None'), ('P', 'Pre-Requisite'), ('C', 'Co-Requisite')], help_text='```json\n{\n    "N": "None",\n    "P": "Pre-Requisite",\n    "C": "Co-Requisite"\n}\n```', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('N', 'None'), ('P', 'Pre-Requisite'), ('C', 'Co-Requisite')], help_text='```json\n{\n    "N": "None",\n    "P": "Pre-Requisite",\n    "C": "Co-Requisite"\n}\n```', max_length=20, null=True),
        ),
    ]
