# Generated by Django 3.2.13 on 2022-06-06 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_cms', '0008_auto_20220605_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='confirmed_count',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='reserved_count',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='addtl_laboratory_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_code',
            field=models.CharField(default='code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_intercollegiate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='laboratory_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='non_professional_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='professional_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='ref_id',
            field=models.CharField(default='code', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_schedules', to='core_cms.schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_cms.curriculumsubject'),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_schedules', to='core_cms.room'),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='time_out',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='ScheduleFees',
        ),
    ]
