# Generated by Django 3.2.13 on 2022-06-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0009_auto_20220607_0941'),
        ('core_cms', '0009_auto_20220606_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core_accounts.personnel'),
        ),
    ]
