# Generated by Django 3.2.13 on 2022-06-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0010_alter_schedule_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='subject',
            new_name='curriculum_subject',
        ),
    ]
