# Generated by Django 3.2.13 on 2022-06-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0011_rename_subject_schedule_curriculum_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='curriculum_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core_cms.curriculumsubject'),
        ),
    ]
