# Generated by Django 3.2.13 on 2022-06-08 11:10

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0012_alter_schedule_curriculum_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type_subjects',
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_type',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('A11', 'AS/CMT/ROTC 11'), ('A12', 'AS/CMT/ROTC 12'), ('A21', 'AS/CMT/ROTC 21'), ('A22', 'AS/CMT/ROTC 22'), ('A31', 'AS/CMT/ROTC 31'), ('A32', 'AS/CMT/ROTC 32'), ('A41', 'AS/CMT/ROTC 41'), ('A42', 'AS/CMT/ROTC 42'), ('PE1', 'PE 1'), ('PE2', 'PE 2'), ('PE3', 'PE 3'), ('PE4', 'PE 4')], help_text='```json\n{\n    "A11": "AS/CMT/ROTC 11",\n    "A12": "AS/CMT/ROTC 12",\n    "A21": "AS/CMT/ROTC 21",\n    "A22": "AS/CMT/ROTC 22",\n    "A31": "AS/CMT/ROTC 31",\n    "A32": "AS/CMT/ROTC 32",\n    "A41": "AS/CMT/ROTC 41",\n    "A42": "AS/CMT/ROTC 42",\n    "PE1": "PE 1",\n    "PE2": "PE 2",\n    "PE3": "PE 3",\n    "PE4": "PE 4"\n}\n```', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CurriculumSubjectRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('type', slu.framework.models.TextChoiceField(choices=[('P', 'Pre-Requisite'), ('C', 'Co-Requisite')], default='P', help_text='```json\n{\n    "P": "Pre-Requisite",\n    "C": "Co-Requisite"\n}\n```', max_length=20)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='core_cms.curriculumsubject')),
                ('requisite_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisite_tags', to='core_cms.curriculumsubject')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
