# Generated by Django 3.2.13 on 2022-06-12 08:40

from django.db import migrations, models
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0013_auto_20220608_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('class_code', models.CharField(max_length=50)),
                ('class_size', models.IntegerField(default=0)),
                ('professional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_professional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('laboratory_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addtl_laboratory_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_dissolved', models.BooleanField(default=False)),
                ('is_crash_course', models.BooleanField(default=False)),
                ('is_intercollegiate', models.BooleanField(default=False)),
                ('is_external_class', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ref_id', models.CharField(max_length=50)),
                ('time_in', models.TimeField(null=True)),
                ('time_out', models.TimeField(null=True)),
                ('day', slu.framework.models.TextChoiceField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], default='M', help_text='```json\n{\n    "M": "Monday",\n    "T": "Tuesday",\n    "W": "Wednesday",\n    "TH": "Thursday",\n    "F": "Friday",\n    "S": "Saturday"\n}\n```', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='curriculum_subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='room',
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='schedule',
        ),
    ]
