# Generated by Django 3.2.13 on 2022-06-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_students', '0006_alter_enrollmentsubjectschedule_subject_class'),
        ('core_accounts', '0009_auto_20220607_0941'),
        ('core_cms', '0014_auto_20220612_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleTime',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='core_cms.class'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to='core_cms.room'),
        ),
        migrations.AddField(
            model_name='class',
            name='curriculum_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='core_cms.curriculumsubject'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_classes', to='core_accounts.personnel'),
        ),
    ]
