# Generated by Django 3.2.13 on 2022-06-12 13:19

import django.core.validators
from django.db import migrations, models
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0015_auto_20220612_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('type', slu.framework.models.TextChoiceField(choices=[('M', 'Miscellaneous Fee'), ('O', 'Other Fee')], help_text='```json\n{\n    "M": "Miscellaneous Fee",\n    "O": "Other Fee"\n}\n```', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('degree_type', slu.framework.models.TextChoiceField(blank=True, choices=[('0', 'Graduate Program')], help_text='```json\n{\n    "0": "Graduate Program"\n}\n```', max_length=10, null=True)),
                ('charge_code', slu.framework.models.TextChoiceField(blank=True, choices=[('P', 'Public Lecture')], help_text='```json\n{\n    "P": "Public Lecture"\n}\n```', max_length=10, null=True)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('semester_from', slu.framework.models.TextChoiceField(blank=True, choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], help_text='```json\n{\n    "FS": "First Semester",\n    "SS": "Second Semester",\n    "S": "Summer"\n}\n```', max_length=10, null=True)),
                ('semester_to', slu.framework.models.TextChoiceField(blank=True, choices=[('FS', 'First Semester'), ('SS', 'Second Semester'), ('S', 'Summer')], help_text='```json\n{\n    "FS": "First Semester",\n    "SS": "Second Semester",\n    "S": "Summer"\n}\n```', max_length=10, null=True)),
                ('total_unit_from', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_unit_to', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year_level_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('year_level_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fees', models.ManyToManyField(blank=True, to='core_cms.Fee')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
