# Generated by Django 3.2.13 on 2022-06-13 04:47

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0016_fee_feespecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='addtl_laboratory_fee',
        ),
        migrations.RemoveField(
            model_name='class',
            name='laboratory_fee',
        ),
        migrations.RemoveField(
            model_name='class',
            name='non_professional_fee',
        ),
        migrations.RemoveField(
            model_name='class',
            name='professional_fee',
        ),
        migrations.AlterField(
            model_name='subject',
            name='no_of_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Only for Medicine Subjects', max_digits=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Only for Non-Medicine Subjects', max_digits=5),
        ),
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('label', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', slu.framework.models.TextChoiceField(choices=[('PF', 'Professional Fee'), ('NPF', 'Non-Professional Fee'), ('LF', 'Laboratory Fee'), ('ALF', 'Additional Laboratory Fee')], default='PF', help_text='```json\n{\n    "PF": "Professional Fee",\n    "NPF": "Non-Professional Fee",\n    "LF": "Laboratory Fee",\n    "ALF": "Additional Laboratory Fee"\n}\n```', max_length=20)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fees', to='core_cms.class')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
