# Generated by Django 3.2.13 on 2022-06-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0017_auto_20220613_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
