# Generated by Django 3.2.13 on 2022-06-17 03:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0010_auto_20220610_1813'),
        ('core_cms', '0019_auto_20220615_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ref_id', models.CharField(max_length=100)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('year_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('label', models.CharField(max_length=250)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', slu.framework.models.TextChoiceField(choices=[('PF', 'Professional Fee'), ('NPF', 'Non-Professional Fee'), ('LF', 'Laboratory Fee'), ('ALF', 'Additional Laboratory Fee')], default='PF', help_text='```json\n{\n    "PF": "Professional Fee",\n    "NPF": "Non-Professional Fee",\n    "LF": "Laboratory Fee",\n    "ALF": "Additional Laboratory Fee"\n}\n```', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_fees', to='core_accounts.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core_cms.subject')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='ClassFee',
        ),
    ]
