# Generated by Django 3.2.13 on 2022-06-22 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0020_auto_20220617_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feespecification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='miscellaneousfeespecification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='otherfeespecification',
            options={},
        ),
        migrations.AddField(
            model_name='feespecification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feespecification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='feespecification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
