# Generated by Django 3.2.13 on 2022-06-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0023_auto_20220624_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumsubject',
            name='curriculum_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='core_cms.curriculumperiod'),
        ),
    ]
