# Generated by Django 3.2.13 on 2022-07-04 05:52

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0013_auto_20220629_0008'),
        ('core_cms', '0024_alter_curriculumsubject_curriculum_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('type', slu.framework.models.TextChoiceField(blank=True, choices=[('S', 'Scholarship'), ('N', 'Normal')], help_text='```json\n{\n    "S": "Scholarship",\n    "N": "Normal"\n}\n```', max_length=10, null=True)),
                ('apply_to', models.JSONField(default=list)),
                ('ref_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('category_rate_exemption', models.JSONField(default=list)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='core_accounts.department')),
                ('fee_exemption', models.ManyToManyField(blank=True, related_name='exempted_discounts', to='core_cms.Fee')),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
