# Generated by Django 3.2.13 on 2022-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0024_alter_curriculumsubject_curriculum_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
