# Generated by Django 3.2.13 on 2022-07-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0025_auto_20220704_1424'),
        ('core_cms', '0025_discount'),
    ]

    operations = [
    ]
