# Generated by Django 3.2.13 on 2022-07-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0026_merge_0025_auto_20220704_1424_0025_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='fee_exemption',
            new_name='fee_exemptions',
        ),
    ]
