# Generated by Django 3.2.13 on 2022-07-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0027_laboratoryfee'),
        ('core_cms', '0027_rename_fee_exemption_discount_fee_exemptions'),
    ]

    operations = [
    ]
