# Generated by Django 3.2.13 on 2022-07-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0014_academicyear_semester'),
        ('core_cms', '0028_merge_20220710_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='feespecification',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='feespecification',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='laboratoryfee',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='laboratoryfee',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='tuitionfeerate',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='tuitionfeerate',
            name='year_start',
        ),
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core_accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='core_accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='feespecification',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_specifications', to='core_accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='laboratoryfee',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratory_fees', to='core_accounts.academicyear'),
        ),
        migrations.AddField(
            model_name='tuitionfeerate',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_fee_rates', to='core_accounts.academicyear'),
        ),
    ]
