# Generated by Django 3.2.14 on 2022-07-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0031_curriculumperiod_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsubject',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_subjects', to='core_cms.curriculum'),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='curriculum_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_subjects', to='core_cms.curriculumperiod'),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='tuition_fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_subjects', to='core_cms.tuitionfeecategory'),
        ),
    ]
