# Generated by Django 3.2.14 on 2022-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0032_auto_20220730_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
