# Generated by Django 3.2.14 on 2022-09-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cms', '0036_auto_20220808_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='curriculum_subject',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core_cms.subject'),
        ),
    ]
