# Generated by Django 3.2.14 on 2022-09-16 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0017_auto_20220916_2114'),
        ('core_cms', '0037_auto_20220910_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core_cms.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core_accounts.semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='year_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
