# Generated by Django 3.2.13 on 2022-06-22 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20220618_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailchannel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificationchannel',
            options={},
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
