# Generated by Django 3.2.14 on 2022-07-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchannel',
            name='enable_whitelist',
            field=models.BooleanField(default=False),
        ),
    ]
