# Generated by Django 3.2.13 on 2022-05-31 08:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_accounts', '0003_auto_20220530_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(slu.framework.models.BaseModelMixin, 'auth.group'),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='roles',
            field=models.ManyToManyField(related_name='modules', through='core_accounts.RoleModule', to='core_accounts.Role'),
        ),
        migrations.AlterField(
            model_name='rolemodule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_accounts.role'),
        ),
        migrations.AlterField(
            model_name='userschoolgroup',
            name='roles',
            field=models.ManyToManyField(to='core_accounts.Role'),
        ),
    ]
