# Generated by Django 3.2.13 on 2022-06-05 21:16

from django.db import migrations
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0006_auto_20220601_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='division_group',
            field=slu.framework.models.TextChoiceField(choices=[('1', 'Tertiary'), ('2', 'Hospital'), ('3', 'Elementary'), ('4', 'High School')], default='1', help_text='```json\n{\n    "1": "Tertiary",\n    "2": "Hospital",\n    "3": "Elementary",\n    "4": "High School"\n}\n```', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='platform',
            field=slu.framework.models.TextChoiceField(choices=[('W', 'Web'), ('M', 'Mobile')], help_text='```json\n{\n    "W": "Web",\n    "M": "Mobile"\n}\n```', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=slu.framework.models.TextChoiceField(choices=[('a', 'Active'), ('l', 'Locked')], default='a', help_text='```json\n{\n    "a": "Active",\n    "l": "Locked"\n}\n```', max_length=2),
        ),
    ]
