# Generated by Django 3.2.13 on 2022-06-07 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0007_auto_20220605_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('ref_id', models.CharField(db_index=True, max_length=50)),
                ('id_code', models.CharField(db_index=True, max_length=50)),
                ('old_id', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', slu.framework.models.TextChoiceField(blank=True, choices=[('O', 'Officer'), ('S', 'S'), ('M', 'M')], help_text='```json\n{\n    "O": "Officer",\n    "S": "S",\n    "M": "M"\n}\n```', max_length=50, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('maiden_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', slu.framework.models.TextChoiceField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='```json\n{\n    "M": "Male",\n    "F": "Female"\n}\n```', max_length=1, null=True)),
                ('civil_status', slu.framework.models.TextChoiceField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed')], help_text='```json\n{\n    "S": "Single",\n    "M": "Married",\n    "W": "Widowed"\n}\n```', max_length=50, null=True)),
                ('nationality', slu.framework.models.TextChoiceField(blank=True, choices=[('F', 'Filipino')], help_text='```json\n{\n    "F": "Filipino"\n}\n```', max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=250, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_child', models.IntegerField(default=0)),
                ('relationship_code', slu.framework.models.TextChoiceField(blank=True, choices=[('RC', 'RC')], help_text='```json\n{\n    "RC": "RC"\n}\n```', max_length=10, null=True)),
                ('sss_no', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.CharField(blank=True, max_length=255, null=True)),
                ('license_no', models.CharField(blank=True, max_length=255, null=True)),
                ('pagibig_no', models.CharField(blank=True, max_length=255, null=True)),
                ('philhealth_no', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('home_phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('baguio_address', models.CharField(blank=True, max_length=250, null=True)),
                ('baguio_phone_no', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('barangay', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_name', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_relationship', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_address', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_phone_no', models.CharField(blank=True, max_length=250, null=True)),
                ('union_affiliation', slu.framework.models.TextChoiceField(blank=True, choices=[('UFESLU', 'UFESLU')], help_text='```json\n{\n    "UFESLU": "UFESLU"\n}\n```', max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=250, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.SoftDeleteMixin, slu.framework.models.BaseModelMixin, models.Model),
        ),
    ]
