# Generated by Django 3.2.13 on 2022-06-10 10:13

from django.db import migrations, models
import django.db.models.deletion
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0009_auto_20220607_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(slu.framework.models.BaseModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='relationship_code',
        ),
        migrations.AddField(
            model_name='personnel',
            name='employee_status',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('R', 'Resigned'), ('T', 'Terminated'), ('C', 'End of Contract'), ('E', 'Retired'), ('D', 'Deceased'), ('N', 'No Load'), ('X', 'Retrenched')], help_text='```json\n{\n    "R": "Resigned",\n    "T": "Terminated",\n    "C": "End of Contract",\n    "E": "Retired",\n    "D": "Deceased",\n    "N": "No Load",\n    "X": "Retrenched"\n}\n```', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='employee_type',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('F', 'Full-Time'), ('P', 'Part-Time')], help_text='```json\n{\n    "F": "Full-Time",\n    "P": "Part-Time"\n}\n```', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='tenure',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('A', 'Casual'), ('C', 'Contractual'), ('E', 'Regular'), ('L', 'Study Leave'), ('O', 'Part-Time'), ('P', 'Permanent'), ('R', 'Probationary'), ('S', 'Sabbatical'), ('U', 'Unknown')], help_text='```json\n{\n    "A": "Casual",\n    "C": "Contractual",\n    "E": "Regular",\n    "L": "Study Leave",\n    "O": "Part-Time",\n    "P": "Permanent",\n    "R": "Probationary",\n    "S": "Sabbatical",\n    "U": "Unknown"\n}\n```', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='union_affiliation',
            field=slu.framework.models.TextChoiceField(blank=True, choices=[('E', 'ELP'), ('U', 'UFESLU'), ('A', 'ALLIANCE')], help_text='```json\n{\n    "E": "ELP",\n    "U": "UFESLU",\n    "A": "ALLIANCE"\n}\n```', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='core_accounts.religion'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='core_accounts.rank'),
        ),
    ]
