# Generated by Django 3.2.14 on 2022-09-17 11:55

from django.conf import settings
from django.db import migrations, models
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0017_auto_20220916_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=slu.framework.models.TextChoiceField(choices=[('B', 'Base'), ('DB', 'Dashboard'), ('CMS', 'CMS'), ('CON', 'Configuration'), ('T', 'Transaction'), ('M', 'Mobile')], default='B', help_text='```json\n{\n    "B": "Base",\n    "DB": "Dashboard",\n    "CMS": "CMS",\n    "CON": "Configuration",\n    "T": "Transaction",\n    "M": "Mobile"\n}\n```', max_length=5),
        ),
        migrations.AddField(
            model_name='module',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='users',
            field=models.ManyToManyField(related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
