# Generated by Django 3.2.14 on 2022-09-26 12:41

from django.db import migrations, models
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0018_auto_20220917_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='type',
            field=slu.framework.models.TextChoiceField(choices=[('C', 'Changed'), ('W', 'Waived')], default='C', help_text='```json\n{\n    "C": "Changed",\n    "W": "Waived"\n}\n```', max_length=2),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='value',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
