# Generated by Django 3.2.14 on 2022-10-25 02:18

from django.db import migrations
import slu.framework.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0019_auto_20220926_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='category',
            field=slu.framework.models.TextChoiceField(choices=[('B', 'Base'), ('DB', 'Dashboard'), ('CMS', 'CMS'), ('CON', 'Configuration'), ('T', 'Transaction'), ('ST', 'Student Request'), ('M', 'Mobile')], default='B', help_text='```json\n{\n    "B": "Base",\n    "DB": "Dashboard",\n    "CMS": "CMS",\n    "CON": "Configuration",\n    "T": "Transaction",\n    "ST": "Student Request",\n    "M": "Mobile"\n}\n```', max_length=5),
        ),
    ]
